<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;
use Faker\Factory as Faker;

class DataTrainingTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $faker = Faker::create('id_ID');
        DB::table('data_training')->insert([
            [
                'nama_anak' => $faker->name,
                'usia' => "32",
                'berat_badan' => "10",
                'tinggi_badan' => "80.8",
                'status' => "Sangat Pendek",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "31",
                'berat_badan' => "12.4",
                'tinggi_badan' => "85",
                'status' => "Pendek",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "46",
                'berat_badan' => "11.9",
                'tinggi_badan' => "91.4",
                'status' => "Pendek",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "37",
                'berat_badan' => "10",
                'tinggi_badan' => "85",
                'status' => "Sangat Pendek",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "45",
                'berat_badan' => "10.7",
                'tinggi_badan' => "86.8",
                'status' => "Sangat Pendek",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "41",
                'berat_badan' => "11.2",
                'tinggi_badan' => "89.5",
                'status' => "Pendek",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "25",
                'berat_badan' => "10.3",
                'tinggi_badan' => "80.7",
                'status' => "Pendek",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "10",
                'berat_badan' => "8.3",
                'tinggi_badan' => "70.4",
                'status' => "Normal",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "34",
                'berat_badan' => "12.2",
                'tinggi_badan' => "90.4",
                'status' => "Normal",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "16",
                'berat_badan' => "8.2",
                'tinggi_badan' => "74.6",
                'status' => "Pendek",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "24",
                'berat_badan' => "10",
                'tinggi_badan' => "83.3",
                'status' => "Normal",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "22",
                'berat_badan' => "8.9",
                'tinggi_badan' => "74.4",
                'status' => "Sangat Pendek",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "42",
                'berat_badan' => "13.5",
                'tinggi_badan' => "92",
                'status' => "Normal",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "7",
                'berat_badan' => "8",
                'tinggi_badan' => "67",
                'status' => "Normal",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "14",
                'berat_badan' => "10.5",
                'tinggi_badan' => "76.3",
                'status' => "Normal",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "52",
                'berat_badan' => "13",
                'tinggi_badan' => "95.4",
                'status' => "Pendek",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "11",
                'berat_badan' => "9.8",
                'tinggi_badan' => "71.6",
                'status' => "Normal",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "50",
                'berat_badan' => "17.5",
                'tinggi_badan' => "103.2",
                'status' => "Normal",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "2",
                'berat_badan' => "3.3",
                'tinggi_badan' => "47.2",
                'status' => "Sangat Pendek",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "36",
                'berat_badan' => "11.2",
                'tinggi_badan' => "87.7",
                'status' => "Pendek",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "36",
                'berat_badan' => "11.7",
                'tinggi_badan' => "85",
                'status' => "Pendek",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "37",
                'berat_badan' => "11.5",
                'tinggi_badan' => "87.7",
                'status' => "Pendek",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "44",
                'berat_badan' => "12.3",
                'tinggi_badan' => "90.2",
                'status' => "Pendek",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "49",
                'berat_badan' => "14.4",
                'tinggi_badan' => "93.4",
                'status' => "Pendek",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "42",
                'berat_badan' => "11.2",
                'tinggi_badan' => "90.5",
                'status' => "Pendek",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "20",
                'berat_badan' => "9.3",
                'tinggi_badan' => "74",
                'status' => "Sangat Pendek",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "43",
                'berat_badan' => "14.5",
                'tinggi_badan' => "93.5",
                'status' => "Normal",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "48",
                'berat_badan' => "12.3",
                'tinggi_badan' => "95.5",
                'status' => "Normal",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "21",
                'berat_badan' => "9",
                'tinggi_badan' => "76.7",
                'status' => "Pendek",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "25",
                'berat_badan' => "9.5",
                'tinggi_badan' => "80",
                'status' => "Pendek",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "36",
                'berat_badan' => "11.5",
                'tinggi_badan' => "88.1",
                'status' => "Pendek",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "48",
                'berat_badan' => "17.8",
                'tinggi_badan' => "95.2",
                'status' => "Normal",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "16",
                'berat_badan' => "10.3",
                'tinggi_badan' => "76.5",
                'status' => "Normal",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "4",
                'berat_badan' => "6",
                'tinggi_badan' => "59.5",
                'status' => "Pendek",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "45",
                'berat_badan' => "10.8",
                'tinggi_badan' => "88",
                'status' => "Sangat Pendek",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "11",
                'berat_badan' => "8",
                'tinggi_badan' => "72.8",
                'status' => "Normal",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "9",
                'berat_badan' => "9",
                'tinggi_badan' => "70",
                'status' => "Normal",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "28",
                'berat_badan' => "11.5",
                'tinggi_badan' => "84.9",
                'status' => "Normal",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "30",
                'berat_badan' => "12.7",
                'tinggi_badan' => "87.5",
                'status' => "Normal",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "1",
                'berat_badan' => "3",
                'tinggi_badan' => "50",
                'status' => "Pendek",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "19",
                'berat_badan' => "9",
                'tinggi_badan' => "72.2",
                'status' => "Sangat Pendek",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "30",
                'berat_badan' => "11",
                'tinggi_badan' => "83",
                'status' => "Pendek",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "42",
                'berat_badan' => "14.3",
                'tinggi_badan' => "95",
                'status' => "Normal",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "22",
                'berat_badan' => "10",
                'tinggi_badan' => "78.1",
                'status' => "Pendek",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "3",
                'berat_badan' => "6.5",
                'tinggi_badan' => "61.4",
                'status' => "Normal",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "37",
                'berat_badan' => "10.4",
                'tinggi_badan' => "86",
                'status' => "Pendek",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "36",
                'berat_badan' => "11.2",
                'tinggi_badan' => "87.7",
                'status' => "Pendek",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "30",
                'berat_badan' => "10",
                'tinggi_badan' => "80.6",
                'status' => "Sangat Pendek",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "31",
                'berat_badan' => "10.4",
                'tinggi_badan' => "82",
                'status' => "Sangat Pendek",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "38",
                'berat_badan' => "10.8",
                'tinggi_badan' => "86.4",
                'status' => "Pendek",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "45",
                'berat_badan' => "10.8",
                'tinggi_badan' => "88",
                'status' => "Sangat Pendek",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "48",
                'berat_badan' => "11.7",
                'tinggi_badan' => "89.2",
                'status' => "Sangat Pendek",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "29",
                'berat_badan' => "9.7",
                'tinggi_badan' => "82.5",
                'status' => "Pendek",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "3",
                'berat_badan' => "6.5",
                'tinggi_badan' => "59.5",
                'status' => "Normal",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "34",
                'berat_badan' => "22",
                'tinggi_badan' => "98.4",
                'status' => "Normal",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "7",
                'berat_badan' => "8.8",
                'tinggi_badan' => "67",
                'status' => "Normal",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "10",
                'berat_badan' => "8.3",
                'tinggi_badan' => "70.4",
                'status' => "Normal",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "15",
                'berat_badan' => "9",
                'tinggi_badan' => "74.5",
                'status' => "Normal",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "23",
                'berat_badan' => "10.8",
                'tinggi_badan' => "90.3",
                'status' => "Normal",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "32",
                'berat_badan' => "12.4",
                'tinggi_badan' => "91.3",
                'status' => "Normal",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "36",
                'berat_badan' => "10.8",
                'tinggi_badan' => "86.4",
                'status' => "Pendek",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "58",
                'berat_badan' => "17.8",
                'tinggi_badan' => "109.5",
                'status' => "Normal",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "23",
                'berat_badan' => "11.6",
                'tinggi_badan' => "81.6",
                'status' => "Normal",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "8",
                'berat_badan' => "7.5",
                'tinggi_badan' => "67.1",
                'status' => "Normal",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "41",
                'berat_badan' => "12.3",
                'tinggi_badan' => "93.8",
                'status' => "Normal",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "2",
                'berat_badan' => "5.5",
                'tinggi_badan' => "55.4",
                'status' => "Normal",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "22",
                'berat_badan' => "9.6",
                'tinggi_badan' => "79.5",
                'status' => "Pendek",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "16",
                'berat_badan' => "8.2",
                'tinggi_badan' => "74.6",
                'status' => "Pendek",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "17",
                'berat_badan' => "8.3",
                'tinggi_badan' => "76.3",
                'status' => "Normal",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "22",
                'berat_badan' => "8.9",
                'tinggi_badan' => "75.6",
                'status' => "Sangat Pendek",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "3",
                'berat_badan' => "5.2",
                'tinggi_badan' => "57",
                'status' => "Pendek",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "26",
                'berat_badan' => "12.3",
                'tinggi_badan' => "84.7",
                'status' => "Normal",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "46",
                'berat_badan' => "14.8",
                'tinggi_badan' => "94.9",
                'status' => "Normal",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "40",
                'berat_badan' => "13",
                'tinggi_badan' => "94.8",
                'status' => "Normal",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "36",
                'berat_badan' => "11",
                'tinggi_badan' => "87",
                'status' => "Pendek",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "51",
                'berat_badan' => "8.3",
                'tinggi_badan' => "76.3",
                'status' => "Sangat Pendek",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "40",
                'berat_badan' => "13",
                'tinggi_badan' => "93",
                'status' => "Normal",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "37",
                'berat_badan' => "10.7",
                'tinggi_badan' => "83.3",
                'status' => "Sangat Pendek",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "36",
                'berat_badan' => "10.7",
                'tinggi_badan' => "83.7",
                'status' => "Sangat Pendek",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "7",
                'berat_badan' => "3.7",
                'tinggi_badan' => "67",
                'status' => "Normal",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "34",
                'berat_badan' => "7.8",
                'tinggi_badan' => "82.2",
                'status' => "Sangat Pendek",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "12",
                'berat_badan' => "8.3",
                'tinggi_badan' => "70",
                'status' => "Pendek",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "40",
                'berat_badan' => "13",
                'tinggi_badan' => "94.6",
                'status' => "Normal",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "40",
                'berat_badan' => "13",
                'tinggi_badan' => "94.6",
                'status' => "Normal",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "35",
                'berat_badan' => "10.7",
                'tinggi_badan' => "85.5",
                'status' => "Pendek",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "9",
                'berat_badan' => "8.8",
                'tinggi_badan' => "71.3",
                'status' => "Normal",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "20",
                'berat_badan' => "9.3",
                'tinggi_badan' => "79.1",
                'status' => "Normal",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "40",
                'berat_badan' => "13",
                'tinggi_badan' => "93",
                'status' => "Normal",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "52",
                'berat_badan' => "14.2",
                'tinggi_badan' => "98.3",
                'status' => "Normal",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "37",
                'berat_badan' => "10.7",
                'tinggi_badan' => "83.3",
                'status' => "Sangat Pendek",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "36",
                'berat_badan' => "10.7",
                'tinggi_badan' => "83.7",
                'status' => "Sangat Pendek",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "7",
                'berat_badan' => "3.7",
                'tinggi_badan' => "67",
                'status' => "Normal",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "34",
                'berat_badan' => "7.8",
                'tinggi_badan' => "82.2",
                'status' => "Sangat Pendek",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "12",
                'berat_badan' => "8.3",
                'tinggi_badan' => "70",
                'status' => "Pendek",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "40",
                'berat_badan' => "13",
                'tinggi_badan' => "94.6",
                'status' => "Normal",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "40",
                'berat_badan' => "13",
                'tinggi_badan' => "94.6",
                'status' => "Normal",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "35",
                'berat_badan' => "10.7",
                'tinggi_badan' => "85.5",
                'status' => "Pendek",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "9",
                'berat_badan' => "8.8",
                'tinggi_badan' => "71.3",
                'status' => "Normal",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "20",
                'berat_badan' => "9.3",
                'tinggi_badan' => "79.1",
                'status' => "Normal",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "40",
                'berat_badan' => "13",
                'tinggi_badan' => "93",
                'status' => "Normal",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "52",
                'berat_badan' => "14.2",
                'tinggi_badan' => "98.3",
                'status' => "Normal",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "56",
                'berat_badan' => "13.8",
                'tinggi_badan' => "99",
                'status' => "Normal",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "40",
                'berat_badan' => "14.6",
                'tinggi_badan' => "97.8",
                'status' => "Normal",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "53",
                'berat_badan' => "17.4",
                'tinggi_badan' => "110.6",
                'status' => "Normal",
            ],
            [
                'nama_anak' => $faker->name,
                'usia' => "55",
                'berat_badan' => "18.4",
                'tinggi_badan' => "110.7",
                'status' => "Normal",
            ],
        ]);
    }
}
